### ISSUE TITLE
[META 27] docs: Add ecs-logging-go-zap to the Elastic doc build

### ISSUE THREAD

**Issue by bmorelli25** [elastic/ecs-logging-go-zap#20]
## To do

- [x] Move docs to asciidoc https://github.com/elastic/ecs-logging-go-zap/pull/29
- [x] Open PR in `elastic/docs` to add to the build https://github.com/elastic/docs/pull/2038
- [x] Open infra ticket to add the `elasticsearch/ci docs` check to this repo https://github.com/elastic/infra/pull/25908
- [x] Add the `elasticsearch/ci docs` webhook to the repo
- [x] Remove content from readme and link to published docs https://github.com/elastic/ecs-logging-go-zap/pull/30

Ping me when you're ready for this step and I can help you out!

**Comment by bmorelli25** [comment]
Doc test command:

```
$GIT_HOME/docs/build_docs --doc $GIT_HOME/ecs-logging-go-zap/docs/index.asciidoc --resource=$GIT_HOME/ecs-logging/docs/ --chunk 1 --open
```

**Comment by bmorelli25** [comment]
Most of this is now complete. Will convert the readme content to Asciidoc tomorrow.
